<a href="https://colab.research.google.com/github/andrewyu602/AI_DL/blob/main/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Questions 1.

In [12]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [13]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [14]:
import numpy as np
ab = np.ones((2,2))
ab[0,0] = 5
ab[1,1] = -1
ab

array([[ 5.,  1.],
       [ 1., -1.]])

In [19]:
naive_relu(ab)

array([[5., 1.],
       [1., 0.]])

In [15]:
bb = np.ones((2,2))
bb[1,1] = 0
bb

array([[1., 1.],
       [1., 0.]])

In [16]:
ab + bb

array([[ 6.,  2.],
       [ 2., -1.]])

In [17]:
c = naive_add(ab, bb)

In [18]:
naive_relu(c)

array([[6., 2.],
       [2., 0.]])

In [8]:
import time

x = np.random.random((20, 100))
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z, 0.)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 0.01 s


In [9]:
t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 2.52 s


# Questions 2

: it is because without using .copy, the actual data, which is used as the input of the function, is changed.

: To prevent the actual data

# Questions 3

: naive version of the code is slower because it utilizes the loop while np.maximum calculates through vectorization.

# Questions 4

In [6]:
import numpy as np
X = np.random.random((50, 15))
Y = np.random.random((15,))

In [7]:
X.shape

(50, 15)

In [8]:
Y.shape

(15,)

In [10]:
X + Y

array([[1.00333364, 0.306809  , 0.91210568, 1.21940765, 1.40880115,
        0.50976583, 0.86035923, 1.42758226, 0.40781609, 0.66401428,
        0.75993635, 1.18966034, 1.02639973, 0.63585744, 0.5887434 ],
       [1.82733095, 0.62278395, 1.05631693, 1.63831461, 1.25059945,
        0.6429447 , 1.12889719, 0.94629717, 1.09931308, 1.39598868,
        1.17620602, 1.11873718, 1.30909785, 0.5511654 , 1.13758288],
       [1.09222512, 0.21469752, 0.92752428, 1.34052779, 0.89196638,
        0.62701407, 0.71602946, 0.72731519, 0.41936532, 0.90452149,
        1.09237347, 1.34959358, 1.45683218, 0.55886198, 0.41615486],
       [1.80419438, 0.76226303, 1.07582708, 1.60977652, 0.64744133,
        0.67093204, 1.4688801 , 0.77873177, 1.1240458 , 1.37485809,
        1.24864751, 1.31488017, 1.23984369, 0.86304908, 0.74337831],
       [1.39949681, 0.5318981 , 0.5969613 , 1.22624342, 0.49767315,
        0.20964069, 1.4846331 , 0.84958301, 0.49219264, 0.93637881,
        0.82152646, 0.98148076, 0.60260001, 

In [11]:
Y = np.expand_dims(y, axis=0) # 행 벡터로 확장한 것

In [12]:
Y

array([[0.41832023, 0.04803445, 0.46214868, 0.77334167, 0.00499024,
        0.42034524, 0.41091893, 0.81557034, 0.52592394, 0.34832171,
        0.42466763, 0.93543085, 0.86291004, 0.35111638, 0.47769095]])

# Questions 5

In [22]:
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])
x.shape

(3, 2)

In [25]:
x = x.reshape((1, 6))
x

array([[0., 1., 2., 3., 4., 5.]])

In [26]:
a = np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
b = np.transpose(a)
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
b.shape

(2, 5)

# Questions 6

In [27]:
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [28]:
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [31]:
x = tf.Variable(tf.random.uniform((2, 2)))
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [32]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [33]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])

In [34]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.23023415, 0.23023415],
        [0.6326771 , 0.6326771 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]

In [31]:
import tensorflow as tf

x = tf.Variable(2.0)
y = tf.Variable(1.0)

with tf.GradientTape() as tape:
    f = x**2 * y + x * y + 3 * y
grad_of_f_wrt_x_and_y = tape.gradient(f, [x,y])

In [32]:
grad_of_f_wrt_x_and_y

[<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>]

# Question 7

In [29]:
import tensorflow as tf
import numpy as np

x = tf.constant(np.array([1., 4., 3.]).reshape(1, 3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3, 2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)

with tf.GradientTape() as tape:
    f = tf.matmul(x, W) + b

grad_of_y_wrt_W_and_b = tape.gradient(f, [W, b])

In [30]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [4., 4.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>]

# Question 8

In [33]:
import tensorflow as tf
import numpy as np

x = tf.constant(np.array([1., 4., 3.]).reshape(1, 3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3, 2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)

# 함수 정의 및 미분
with tf.GradientTape() as tape:
    tape.watch([W, b])
    f = tf.pow(tf.matmul(x, W) + b, 3)

# 미분 수행
grad_of_y_wrt_W_and_b = tape.gradient(f, [W, b])

In [34]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 41.4384 ,  32.05867],
        [165.7536 , 128.23468],
        [124.3152 ,  96.17601]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([41.4384 , 32.05867], dtype=float32)>]

# Question 8

In [35]:
import tensorflow as tf

class NaiveDense:
    def __init__(self, input_size, output_size, activation):
        self.activation = activation

        w_shape = (input_size, output_size)
        w_initial_value = tf.random.uniform(w_shape, minval=0, maxval=1e-1)
        self.W = tf.Variable(w_initial_value)

        b_shape = (output_size,)
        b_initial_value = tf.zeros(b_shape)
        self.b = tf.Variable(b_initial_value)

    def __call__(self, inputs):
        return self.activation(tf.matmul(inputs, self.W) + self.b)

    @property
    def weights(self):
        return [self.W, self.b]

In [36]:
exD = NaiveDense( 5, 10, activation = tf.nn.relu)
exD.weights[0].shape

TensorShape([5, 10])

In [37]:
exD

# Question 9

In [38]:
class NaiveSequential:
    def __init__(self, layers):
        self.layers = layers

    def __call__(self, inputs):
        x = inputs
        for layer in self.layers:
           x = layer(x)
        return x

    @property
    def weights(self):
       weights = []
       for layer in self.layers:
           weights += layer.weights
       return weights

In [39]:
model = NaiveSequential([
    NaiveDense(input_size=28 * 28, output_size=512, activation=tf.nn.relu),
    NaiveDense(input_size=512, output_size=10, activation=tf.nn.softmax)
])
assert len(model.weights) == 4

In [40]:
model

In [41]:
import math

class BatchGenerator:
    def __init__(self, images, labels, batch_size=128):
        assert len(images) == len(labels)
        self.index = 0
        self.images = images
        self.labels = labels
        self.batch_size = batch_size
        self.num_batches = math.ceil(len(images) / batch_size)

    def next(self):
        images = self.images[self.index : self.index + self.batch_size]
        labels = self.labels[self.index : self.index + self.batch_size]
        self.index += self.batch_size
        return images, labels

In [42]:
def one_training_step(model, images_batch, labels_batch):
    with tf.GradientTape() as tape:
        predictions = model(images_batch)
        per_sample_losses = tf.keras.losses.sparse_categorical_crossentropy(
            labels_batch, predictions)
        average_loss = tf.reduce_mean(per_sample_losses)
    gradients = tape.gradient(average_loss, model.weights)
    update_weights(gradients, model.weights)
    return average_loss

In [43]:
learning_rate = 1e-3

def update_weights(gradients, weights):
    for g, w in zip(gradients, weights):
        w.assign_sub(g * learning_rate)

In [44]:
from tensorflow.keras import optimizers

optimizer = optimizers.SGD(learning_rate=1e-3)

def update_weights(gradients, weights):
    optimizer.apply_gradients(zip(gradients, weights))

In [45]:
def fit(model, images, labels, epochs, batch_size=128):
    for epoch_counter in range(epochs):
        print(f"Epoch {epoch_counter}")
        batch_generator = BatchGenerator(images, labels)
        for batch_counter in range(batch_generator.num_batches):
            images_batch, labels_batch = batch_generator.next()
            loss = one_training_step(model, images_batch, labels_batch)
            if batch_counter % 100 == 0:
                print(f"loss at batch {batch_counter}: {loss:.2f}")

In [46]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

fit(model, train_images, train_labels, epochs=10, batch_size=128)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Epoch 0
loss at batch 0: 6.41
loss at batch 100: 2.23
loss at batch 200: 2.20
loss at batch 300: 2.08
loss at batch 400: 2.19
Epoch 1
loss at batch 0: 1.87
loss at batch 100: 1.86
loss at batch 200: 1.82
loss at batch 300: 1.69
loss at batch 400: 1.79
Epoch 2
loss at batch 0: 1.55
loss at batch 100: 1.56
loss at batch 200: 1.49
loss at batch 300: 1.41
loss at batch 400: 1.46
Epoch 3
loss at batch 0: 1.29
loss at batch 100: 1.33
loss at batch 200: 1.23
loss at batch 300: 1.19
loss at batch 400: 1.24
Epoch 4
loss at batch 0: 1.10
loss at batch 100: 1.15
loss at batch 200: 1.04
loss at batch 300: 1.03
loss at batch 400: 1.08
Epoch 5
loss at batch 0: 0.96
loss at batch 100: 1.01
loss at batch 200: 0.90
loss at batch 300: 0.92
loss at batch 400: 0.96
Epoch 6
loss at batch 0: 0.85
loss at batch 100: 0.90
loss at batch 200: 0.80
loss at batch 300: 0.83
loss at batch 400: 0.88
Epoch 7
loss at batch 0: 0.78
loss at batch 100: 0.82
loss at batch

In [47]:
predictions = model(test_images)
predictions = predictions.numpy()
predicted_labels = np.argmax(predictions, axis=1)
matches = predicted_labels == test_labels
print(f"accuracy: {matches.mean():.2f}")

accuracy: 0.82
