<a href="https://colab.research.google.com/github/andrewyu602/AI_DL/blob/main/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Questions 1.

In [12]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [13]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [14]:
import numpy as np
ab = np.ones((2,2))
ab[0,0] = 5
ab[1,1] = -1
ab

array([[ 5.,  1.],
       [ 1., -1.]])

In [19]:
naive_relu(ab)

array([[5., 1.],
       [1., 0.]])

In [15]:
bb = np.ones((2,2))
bb[1,1] = 0
bb

array([[1., 1.],
       [1., 0.]])

In [16]:
ab + bb

array([[ 6.,  2.],
       [ 2., -1.]])

In [17]:
c = naive_add(ab, bb)

In [18]:
naive_relu(c)

array([[6., 2.],
       [2., 0.]])

In [8]:
import time

x = np.random.random((20, 100))
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z, 0.)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 0.01 s


In [9]:
t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 2.52 s


# Questions 2

: it is because without using .copy, the actual data, which is used as the input of the function, is changed.

: To prevent the actual data

# Questions 3

: naive version of the code is slower because it utilizes the loop while np.maximum calculates through vectorization.

# Questions 4

In [20]:
import numpy as np
X = np.random.random((32, 10))
y = np.random.random((10,))

In [21]:
X.shape

(32, 10)

In [22]:
y.shape

(10,)

In [23]:
X + y

array([[1.17825447, 1.5204434 , 0.98074448, 1.16248373, 0.45765502,
        0.74480841, 1.37219831, 0.40704592, 0.5948741 , 0.90141034],
       [1.07013865, 0.84694728, 1.00466291, 0.5591615 , 0.73429737,
        1.01030453, 1.50561924, 0.41658531, 0.51386158, 0.95876238],
       [1.0797856 , 1.15632116, 1.75177719, 1.13312437, 0.43806594,
        1.15296168, 1.4503682 , 0.79401095, 0.60224659, 0.99873733],
       [1.21804921, 1.11676866, 0.89084253, 0.93236084, 0.70002179,
        1.42204905, 1.39401294, 0.96829639, 0.06888455, 1.05951342],
       [0.52803584, 0.57639442, 1.8429411 , 0.76815931, 0.45765261,
        1.45415898, 1.06996839, 0.83285646, 0.52284532, 0.67465764],
       [1.23219737, 1.23790764, 1.55805879, 0.59814444, 1.23602904,
        1.11854465, 1.07720227, 1.06835524, 0.74648765, 1.03560535],
       [0.6542007 , 1.46120847, 1.2885278 , 0.51148725, 0.67642593,
        1.29432647, 1.27718194, 0.43526474, 0.49239508, 1.14441646],
       [0.38321183, 0.91045327, 1.6366132

In [25]:
y = np.expand_dims(y, axis=0) # 행 벡터로 확장한 것

In [26]:
y

array([[[0.38074793, 0.54253696, 0.87382313, 0.28541317, 0.24665602,
         0.73403827, 0.57252156, 0.08723326, 0.04842194, 0.56429318]]])

# Questions 5

# Questions 6

In [27]:
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [28]:
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [31]:
x = tf.Variable(tf.random.uniform((2, 2)))
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [32]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [33]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])

In [34]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.23023415, 0.23023415],
        [0.6326771 , 0.6326771 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]

In [1]:
import tensorflow as tf

x = tf.Variable(2.0)
y = tf.Variable(1.0)

with tf.GradientTape() as tape:
    f = x**2 * y + x * y + 3 * y
grad_x, grad_y = tape.gradient(f, [x,y])

In [2]:
grad_x

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [3]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>